/* Fictional scenarios only. Decimal values stay strings until display formatting. */
window.SECReconDemo = {
  companies: [
    {
      name: "Northstar Semiconductor",
      ticker: "NSCT",
      cik: "0009000001",
      period: "Dec 31, 2025",
      filed: "Feb 20, 2026",
      original: "0009000001-26-000014",
      amendment: "0009000001-26-000019",
      scenario: "Changed figures",
      status: "Review changes",
      rows: [
        {
          concept: "Revenue",
          key: "RevenueFromContractWithCustomerExcludingAssessedTax",
          before: "1248000000",
          after: "1273000000",
          delta: "+25,000,000",
          status: "changed",
          period: "Jan 1 – Dec 31, 2025",
          kind: "duration",
          unit: "USD",
          note: "Same concept, unit and reporting period. The amendment reports a higher value.",
        },
        {
          concept: "Total assets",
          key: "Assets",
          before: "3840000000",
          after: "3840000000",
          delta: "0",
          status: "unchanged",
          period: "Dec 31, 2025",
          kind: "instant",
          unit: "USD",
          note: "Both filings report the same value. Each keeps its own accession and provenance.",
        },
        {
          concept: "Net income",
          key: "NetIncomeLoss",
          before: "186000000",
          after: "204000000",
          delta: "+18,000,000",
          status: "changed",
          period: "Jan 1 – Dec 31, 2025",
          kind: "duration",
          unit: "USD",
          note: "A comparable value changed. This observation alone does not explain the business reason.",
        },
        {
          concept: "Operating cash flow",
          key: "NetCashProvidedByUsedInOperatingActivities",
          before: "312000000",
          after: null,
          delta: null,
          status: "only_in_original",
          period: "Jan 1 – Dec 31, 2025",
          kind: "duration",
          unit: "USD",
          note: "Not observed in the selected amendment snapshot. This is a coverage gap, not a deletion or zero.",
        },
        {
          concept: "Long-term debt",
          key: "LongTermDebtCurrent",
          before: "450000000",
          after: "420000000 / 425000000",
          delta: null,
          status: "ambiguous",
          period: "Dec 31, 2025",
          kind: "instant",
          unit: "USD",
          note: "The amendment has conflicting observations for this key. No single value or delta is selected.",
        },
        {
          concept: "Cash & equivalents",
          key: "CashAndCashEquivalentsAtCarryingValue",
          before: "640000000",
          after: "640000000",
          delta: "0",
          status: "unchanged",
          period: "Dec 31, 2025",
          kind: "instant",
          unit: "USD",
          note: "Matching values remain separately traceable to both filings.",
        },
      ],
    },
    {
      name: "Meridian Cloud Systems",
      ticker: "MCLD",
      cik: "0009000002",
      period: "Dec 31, 2025",
      filed: "Mar 2, 2026",
      original: "0009000002-26-000008",
      amendment: "0009000002-26-000011",
      scenario: "Formatting amendment",
      status: "No value changes",
      rows: [
        {
          concept: "Revenue",
          key: "RevenueFromContractWithCustomerExcludingAssessedTax",
          before: "824000000",
          after: "824000000",
          delta: "0",
          status: "unchanged",
          period: "Jan 1 – Dec 31, 2025",
          kind: "duration",
          unit: "USD",
          note: "An amended filing does not necessarily change financial facts.",
        },
        {
          concept: "Total assets",
          key: "Assets",
          before: "1860000000",
          after: "1860000000",
          delta: "0",
          status: "unchanged",
          period: "Dec 31, 2025",
          kind: "instant",
          unit: "USD",
          note: "Identical supported observations; this demo does not compare narrative text.",
        },
      ],
    },
    {
      name: "Atlas Energy Holdings",
      ticker: "ATEN",
      cik: "0009000003",
      period: "Dec 31, 2025",
      filed: "Mar 5, 2026",
      original: "0009000003-26-000003",
      amendment: "0009000003-26-000009",
      scenario: "No amendment facts",
      status: "Incomplete coverage",
      rows: [
        {
          concept: "Total assets",
          key: "Assets",
          before: "2310000000",
          after: null,
          delta: null,
          status: "only_in_original",
          period: "Dec 31, 2025",
          kind: "instant",
          unit: "USD",
          note: "The amendment has no supported observations in this snapshot. It may cover non-financial disclosures. The original is preserved.",
        },
      ],
    },
  ],
  jobs: [
    {
      id: "job-1042",
      company: "Northstar Semiconductor",
      kind: "Normalize facts",
      status: "succeeded",
      attempts: 1,
      time: "12:04:18",
      events: [
        "12:04:16 · Accepted in PostgreSQL",
        "12:04:16 · Delivered through Redis",
        "12:04:17 · Lease acquired by worker-02",
        "12:04:18 · Facts and provenance committed",
        "12:04:18 · Delivery acknowledged",
      ],
    },
    {
      id: "job-1041",
      company: "Meridian Cloud Systems",
      kind: "Fetch Company Facts",
      status: "retry_wait",
      attempts: 2,
      time: "12:03:52",
      events: [
        "12:03:30 · First fetch received HTTP 429",
        "12:03:31 · Response body preserved",
        "12:03:52 · Second attempt deferred",
        "12:04:52 · Next attempt due; Retry-After respected",
      ],
    },
    {
      id: "job-1039",
      company: "Atlas Energy Holdings",
      kind: "Normalize facts",
      status: "quarantined",
      attempts: 1,
      time: "12:02:41",
      events: [
        "12:02:40 · Source archived with checksum",
        "12:02:41 · Required numeric field had object type",
        "12:02:41 · No partial facts committed",
        "12:02:41 · Source retained for adapter investigation",
      ],
    },
    {
      id: "job-1038",
      company: "Northstar Semiconductor",
      kind: "Fetch document",
      status: "dead_letter",
      attempts: 5,
      time: "12:01:09",
      events: [
        "11:50:02 · Fetch accepted",
        "11:50–12:01 · Five transient failures with backoff",
        "12:01:09 · Retry budget exhausted",
        "12:01:09 · Dead-letter record retained",
      ],
    },
    {
      id: "job-1037",
      company: "Meridian Cloud Systems",
      kind: "Reconcile pair",
      status: "succeeded",
      attempts: 1,
      time: "12:00:48",
      events: [
        "12:00:47 · Selected immutable snapshots",
        "12:00:48 · Comparison stored: unchanged",
        "12:00:48 · Evidence links recorded",
      ],
    },
  ],
  steps: [
    {
      page: "overview",
      title: "Start with the operating picture",
      text: "This screen answers: is data arriving, is processing healthy, and what needs attention? These numbers are sample telemetry for the future operations interface, not live M4 metrics.",
    },
    {
      page: "filings",
      title: "Choose a filing, not just a company",
      text: "An accession identifies one legal filing. Original and amended filings remain separate records. Open any row to compare its pair; search by the fictional name or ticker.",
    },
    {
      page: "comparisons",
      title: "Read a change in context",
      text: "A value is compared only when concept, unit and reporting dates match. Try the three scenarios. “Only in original” means missing coverage, not deleted data. “Ambiguous” means no single value can safely be chosen.",
    },
    {
      page: "comparisons",
      title: "Follow the evidence",
      text: "Click a financial row to open its source drawer. The accession, reporting period, snapshot, checksum and JSON locator explain exactly where that assertion came from. The drawer also distinguishes fictional metadata from real backend evidence.",
    },
    {
      page: "jobs",
      title: "A failure is an inspectable event",
      text: "Select a job to see its attempt history. A retry waits until its due time. Quarantine preserves unexpected input. Redrive the dead-letter job to create a NEW linked job while keeping the old failure intact. All actions here are simulated.",
    },
    {
      page: "archive",
      title: "Keep the source before transforming it",
      text: "Checksums identify body content; event IDs identify captures. Multiple captures can share identical bytes. This archive view is the basis for reproducing old results without fetching SEC again.",
    },
    {
      page: "replay",
      title: "Rebuild without destroying the current view",
      text: "Run the simulated replay. It builds a separate generation from preserved sources, checks its digest and leaves the current generation available. A real restore of job history additionally needs a database backup.",
    },
  ],
};
